# Generated by Django 5.1.2 on 2025-01-14 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_rename_message_message_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='image',
            field=models.ImageField(blank=True, default='media/default.png', null=True, upload_to='media/'),
        ),
    ]
